project_name = "lustrous-bit-313410"
vpc_name     = "infra-manager-vpc"
region       = "asia-south1"
zone         = "asia-south1-a"
subnet       = "infra-manager-subnet"
vm_name      = "infra-manager-instance"
machine_type = "e2-micro"