project_name = "lustrous-bit-313410"
vpc_name     = "infra-manager-sample-vpc"
region       = "asia-south1"
zone         = "asia-south1-a"
subnet       = "infra-manager-sample-subnet"
vm_name      = "infra-manager-sample-instance"
machine_type = "e2-micro"