project_name = "lustrous-bit-313410"
vpc_name     = "test-vpc"
region       = "asia-south1"
zone         = "asia-south1-a"
subnet       = "test-subnet"
vm_name      = "test-instance"
machine_type = "e2-micro"